/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	clusterregisterv1alpha1 "Hybrid_Cloud/pkg/apis/clusterregister/v1alpha1"
	versioned "Hybrid_Cloud/pkg/client/clusterregister/v1alpha1/clientset/versioned"
	internalinterfaces "Hybrid_Cloud/pkg/client/clusterregister/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "Hybrid_Cloud/pkg/client/clusterregister/v1alpha1/listers/clusterregister/v1alpha1"
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterRegisterInformer provides access to a shared informer and lister for
// ClusterRegisters.
type ClusterRegisterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterRegisterLister
}

type clusterRegisterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterRegisterInformer constructs a new informer for ClusterRegister type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterRegisterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterRegisterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterRegisterInformer constructs a new informer for ClusterRegister type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterRegisterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HcpV1alpha1().ClusterRegisters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HcpV1alpha1().ClusterRegisters(namespace).Watch(context.TODO(), options)
			},
		},
		&clusterregisterv1alpha1.ClusterRegister{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterRegisterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterRegisterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterRegisterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterregisterv1alpha1.ClusterRegister{}, f.defaultInformer)
}

func (f *clusterRegisterInformer) Lister() v1alpha1.ClusterRegisterLister {
	return v1alpha1.NewClusterRegisterLister(f.Informer().GetIndexer())
}
