/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "Hybrid_Cloud/pkg/apis/resource/v1alpha1"
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHCPPods implements HCPPodInterface
type FakeHCPPods struct {
	Fake *FakeHcpV1alpha1
	ns   string
}

var hcppodsResource = schema.GroupVersionResource{Group: "hcp.crd.com", Version: "v1alpha1", Resource: "hcppods"}

var hcppodsKind = schema.GroupVersionKind{Group: "hcp.crd.com", Version: "v1alpha1", Kind: "HCPPod"}

// Get takes name of the hCPPod, and returns the corresponding hCPPod object, and an error if there is any.
func (c *FakeHCPPods) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HCPPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hcppodsResource, c.ns, name), &v1alpha1.HCPPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPPod), err
}

// List takes label and field selectors, and returns the list of HCPPods that match those selectors.
func (c *FakeHCPPods) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HCPPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hcppodsResource, hcppodsKind, c.ns, opts), &v1alpha1.HCPPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HCPPodList{ListMeta: obj.(*v1alpha1.HCPPodList).ListMeta}
	for _, item := range obj.(*v1alpha1.HCPPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hCPPods.
func (c *FakeHCPPods) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hcppodsResource, c.ns, opts))

}

// Create takes the representation of a hCPPod and creates it.  Returns the server's representation of the hCPPod, and an error, if there is any.
func (c *FakeHCPPods) Create(ctx context.Context, hCPPod *v1alpha1.HCPPod, opts v1.CreateOptions) (result *v1alpha1.HCPPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hcppodsResource, c.ns, hCPPod), &v1alpha1.HCPPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPPod), err
}

// Update takes the representation of a hCPPod and updates it. Returns the server's representation of the hCPPod, and an error, if there is any.
func (c *FakeHCPPods) Update(ctx context.Context, hCPPod *v1alpha1.HCPPod, opts v1.UpdateOptions) (result *v1alpha1.HCPPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hcppodsResource, c.ns, hCPPod), &v1alpha1.HCPPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPPod), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHCPPods) UpdateStatus(ctx context.Context, hCPPod *v1alpha1.HCPPod, opts v1.UpdateOptions) (*v1alpha1.HCPPod, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hcppodsResource, "status", c.ns, hCPPod), &v1alpha1.HCPPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPPod), err
}

// Delete takes name of the hCPPod and deletes it. Returns an error if one occurs.
func (c *FakeHCPPods) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hcppodsResource, c.ns, name, opts), &v1alpha1.HCPPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHCPPods) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hcppodsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HCPPodList{})
	return err
}

// Patch applies the patch and returns the patched hCPPod.
func (c *FakeHCPPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HCPPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hcppodsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HCPPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPPod), err
}
