/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "Hybrid_Cloud/pkg/apis/resource/v1alpha1"
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHCPHybridAutoScalers implements HCPHybridAutoScalerInterface
type FakeHCPHybridAutoScalers struct {
	Fake *FakeHcpV1alpha1
	ns   string
}

var hcphybridautoscalersResource = schema.GroupVersionResource{Group: "hcp.crd.com", Version: "v1alpha1", Resource: "hcphybridautoscalers"}

var hcphybridautoscalersKind = schema.GroupVersionKind{Group: "hcp.crd.com", Version: "v1alpha1", Kind: "HCPHybridAutoScaler"}

// Get takes name of the hCPHybridAutoScaler, and returns the corresponding hCPHybridAutoScaler object, and an error if there is any.
func (c *FakeHCPHybridAutoScalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HCPHybridAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hcphybridautoscalersResource, c.ns, name), &v1alpha1.HCPHybridAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPHybridAutoScaler), err
}

// List takes label and field selectors, and returns the list of HCPHybridAutoScalers that match those selectors.
func (c *FakeHCPHybridAutoScalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HCPHybridAutoScalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hcphybridautoscalersResource, hcphybridautoscalersKind, c.ns, opts), &v1alpha1.HCPHybridAutoScalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HCPHybridAutoScalerList{ListMeta: obj.(*v1alpha1.HCPHybridAutoScalerList).ListMeta}
	for _, item := range obj.(*v1alpha1.HCPHybridAutoScalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hCPHybridAutoScalers.
func (c *FakeHCPHybridAutoScalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hcphybridautoscalersResource, c.ns, opts))

}

// Create takes the representation of a hCPHybridAutoScaler and creates it.  Returns the server's representation of the hCPHybridAutoScaler, and an error, if there is any.
func (c *FakeHCPHybridAutoScalers) Create(ctx context.Context, hCPHybridAutoScaler *v1alpha1.HCPHybridAutoScaler, opts v1.CreateOptions) (result *v1alpha1.HCPHybridAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hcphybridautoscalersResource, c.ns, hCPHybridAutoScaler), &v1alpha1.HCPHybridAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPHybridAutoScaler), err
}

// Update takes the representation of a hCPHybridAutoScaler and updates it. Returns the server's representation of the hCPHybridAutoScaler, and an error, if there is any.
func (c *FakeHCPHybridAutoScalers) Update(ctx context.Context, hCPHybridAutoScaler *v1alpha1.HCPHybridAutoScaler, opts v1.UpdateOptions) (result *v1alpha1.HCPHybridAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hcphybridautoscalersResource, c.ns, hCPHybridAutoScaler), &v1alpha1.HCPHybridAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPHybridAutoScaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHCPHybridAutoScalers) UpdateStatus(ctx context.Context, hCPHybridAutoScaler *v1alpha1.HCPHybridAutoScaler, opts v1.UpdateOptions) (*v1alpha1.HCPHybridAutoScaler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hcphybridautoscalersResource, "status", c.ns, hCPHybridAutoScaler), &v1alpha1.HCPHybridAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPHybridAutoScaler), err
}

// Delete takes name of the hCPHybridAutoScaler and deletes it. Returns an error if one occurs.
func (c *FakeHCPHybridAutoScalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hcphybridautoscalersResource, c.ns, name, opts), &v1alpha1.HCPHybridAutoScaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHCPHybridAutoScalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hcphybridautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HCPHybridAutoScalerList{})
	return err
}

// Patch applies the patch and returns the patched hCPHybridAutoScaler.
func (c *FakeHCPHybridAutoScalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HCPHybridAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hcphybridautoscalersResource, c.ns, name, pt, data, subresources...), &v1alpha1.HCPHybridAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HCPHybridAutoScaler), err
}
