#!/bin/bash

# kubectl register platform clustername 
if [ -z "$1" ]; then 
    echo "ERROR: Input PlatformType"
    exit 0
fi

if [ -z "$2" ]; then 
    echo "ERROR: Input Cluster Name"
    exit 0
fi

cd ~/.kube
touch kubeconfig
export KUBECONFIG="~/.kube/kubeconfig"

# cat /dev/null > kubeconfig

case "$1" in 
    "aks") 
        if [ -z "$3" ]; then
            echo "ERROR: Input ResourceGroup"
            exit 0
        fi
        az aks get-credentials --resource-group "$3" --name "$2" --file ~/.kube/kubeconfig
        exit 0
        ;;
    "eks")
        aws eks update-kubeconfig --name "$2"
        exit 0
        ;;
    "gke")
        gcloud container clusters get-credentials "$2"
        exit 0
        ;;
    *)
        echo "ERROR: Platform is wrong"
        exit 0
        ;;
esac
export KUBECONFIG=~/.kube/config