// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPHybridAutoScaler) DeepCopyInto(out *HCPHybridAutoScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPHybridAutoScaler.
func (in *HCPHybridAutoScaler) DeepCopy() *HCPHybridAutoScaler {
	if in == nil {
		return nil
	}
	out := new(HCPHybridAutoScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCPHybridAutoScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCPHybridAutoScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPHybridAutoScalerList) DeepCopyInto(out *HCPHybridAutoScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HCPHybridAutoScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPHybridAutoScalerList.
func (in *HCPHybridAutoScalerList) DeepCopy() *HCPHybridAutoScalerList {
	if in == nil {
		return nil
	}
	out := new(HCPHybridAutoScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPHybridAutoScalerSpec) DeepCopyInto(out *HCPHybridAutoScalerSpec) {
	*out = *in
	in.ScalingOptions.DeepCopyInto(&out.ScalingOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPHybridAutoScalerSpec.
func (in *HCPHybridAutoScalerSpec) DeepCopy() *HCPHybridAutoScalerSpec {
	if in == nil {
		return nil
	}
	out := new(HCPHybridAutoScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPHybridAutoScalerStatus) DeepCopyInto(out *HCPHybridAutoScalerStatus) {
	*out = *in
	in.LastSpec.DeepCopyInto(&out.LastSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPHybridAutoScalerStatus.
func (in *HCPHybridAutoScalerStatus) DeepCopy() *HCPHybridAutoScalerStatus {
	if in == nil {
		return nil
	}
	out := new(HCPHybridAutoScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingOptions) DeepCopyInto(out *ScalingOptions) {
	*out = *in
	in.HpaTemplate.DeepCopyInto(&out.HpaTemplate)
	in.VpaTemplate.DeepCopyInto(&out.VpaTemplate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingOptions.
func (in *ScalingOptions) DeepCopy() *ScalingOptions {
	if in == nil {
		return nil
	}
	out := new(ScalingOptions)
	in.DeepCopyInto(out)
	return out
}
