/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "Hybrid_Cloud/pkg/apis/clusterregister/v1alpha1"
	scheme "Hybrid_Cloud/pkg/client/clusterregister/v1alpha1/clientset/versioned/scheme"
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterRegistersGetter has a method to return a ClusterRegisterInterface.
// A group's client should implement this interface.
type ClusterRegistersGetter interface {
	ClusterRegisters(namespace string) ClusterRegisterInterface
}

// ClusterRegisterInterface has methods to work with ClusterRegister resources.
type ClusterRegisterInterface interface {
	Create(ctx context.Context, clusterRegister *v1alpha1.ClusterRegister, opts v1.CreateOptions) (*v1alpha1.ClusterRegister, error)
	Update(ctx context.Context, clusterRegister *v1alpha1.ClusterRegister, opts v1.UpdateOptions) (*v1alpha1.ClusterRegister, error)
	UpdateStatus(ctx context.Context, clusterRegister *v1alpha1.ClusterRegister, opts v1.UpdateOptions) (*v1alpha1.ClusterRegister, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterRegister, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterRegisterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterRegister, err error)
	// ClusterRegisterExpansion
}

// clusterRegisters implements ClusterRegisterInterface
type clusterRegisters struct {
	client rest.Interface
	ns     string
}

// newClusterRegisters returns a ClusterRegisters
func newClusterRegisters(c *HcpV1alpha1Client, namespace string) *clusterRegisters {
	return &clusterRegisters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterRegister, and returns the corresponding clusterRegister object, and an error if there is any.
func (c *clusterRegisters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterRegister, err error) {
	result = &v1alpha1.ClusterRegister{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterregisters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterRegisters that match those selectors.
func (c *clusterRegisters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterRegisterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterRegisterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterregisters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterRegisters.
func (c *clusterRegisters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterregisters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterRegister and creates it.  Returns the server's representation of the clusterRegister, and an error, if there is any.
func (c *clusterRegisters) Create(ctx context.Context, clusterRegister *v1alpha1.ClusterRegister, opts v1.CreateOptions) (result *v1alpha1.ClusterRegister, err error) {
	result = &v1alpha1.ClusterRegister{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterregisters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterRegister).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterRegister and updates it. Returns the server's representation of the clusterRegister, and an error, if there is any.
func (c *clusterRegisters) Update(ctx context.Context, clusterRegister *v1alpha1.ClusterRegister, opts v1.UpdateOptions) (result *v1alpha1.ClusterRegister, err error) {
	result = &v1alpha1.ClusterRegister{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterregisters").
		Name(clusterRegister.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterRegister).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterRegisters) UpdateStatus(ctx context.Context, clusterRegister *v1alpha1.ClusterRegister, opts v1.UpdateOptions) (result *v1alpha1.ClusterRegister, err error) {
	result = &v1alpha1.ClusterRegister{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterregisters").
		Name(clusterRegister.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterRegister).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterRegister and deletes it. Returns an error if one occurs.
func (c *clusterRegisters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterregisters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterRegisters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterregisters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterRegister.
func (c *clusterRegisters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterRegister, err error) {
	result = &v1alpha1.ClusterRegister{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterregisters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
