// Code generated by protoc-gen-go.
// source: proto/v1/cmd/cmd.proto
// DO NOT EDIT!

/*
Package Hybrid_Cluster_proto_v1_cmd is a generated protocol buffer package.

It is generated from these files:
	proto/v1/cmd/cmd.proto

It has these top-level messages:
	Output
	AKSAddon
	ListAddonRequest
	ListAddonResponse
*/
package cmd

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Output struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}

type AKSAddon struct {
	ResourceGroupName          string `protobuf:"bytes,1,opt" json:"ResourceGroupName,omitempty"`
	ClusterName                string `protobuf:"bytes,2,opt" json:"ClusterName,omitempty"`
	Addon                      string `protobuf:"bytes,3,opt" json:"Addon,omitempty"`
	AppgwID                    string `protobuf:"bytes,4,opt" json:"AppgwID,omitempty"`
	AppgwName                  string `protobuf:"bytes,5,opt" json:"AppgwName,omitempty"`
	AppgwSubnetCidr            string `protobuf:"bytes,6,opt" json:"AppgwSubnetCidr,omitempty"`
	AppgwSubnetID              string `protobuf:"bytes,7,opt" json:"AppgwSubnetID,omitempty"`
	AppgwSubnetPrefix          string `protobuf:"bytes,8,opt" json:"AppgwSubnetPrefix,omitempty"`
	AppgwWatchNamespace        string `protobuf:"bytes,9,opt" json:"AppgwWatchNamespace,omitempty"`
	EnableMsiAuthForMonitoring bool   `protobuf:"varint,10,opt" json:"EnableMsiAuthForMonitoring,omitempty"`
	EnableSecretRotation       bool   `protobuf:"varint,11,opt" json:"EnableSecretRotation,omitempty"`
	EnableSgxquotehelper       bool   `protobuf:"varint,12,opt" json:"EnableSgxquotehelper,omitempty"`
	SubnetName                 string `protobuf:"bytes,13,opt" json:"SubnetName,omitempty"`
	WorkspaceResourceID        string `protobuf:"bytes,14,opt" json:"WorkspaceResourceID,omitempty"`
}

func (m *AKSAddon) Reset()         { *m = AKSAddon{} }
func (m *AKSAddon) String() string { return proto.CompactTextString(m) }
func (*AKSAddon) ProtoMessage()    {}

type ListAddonRequest struct {
	AksAddon *AKSAddon `protobuf:"bytes,1,opt,name=aks_addon" json:"aks_addon,omitempty"`
}

func (m *ListAddonRequest) Reset()         { *m = ListAddonRequest{} }
func (m *ListAddonRequest) String() string { return proto.CompactTextString(m) }
func (*ListAddonRequest) ProtoMessage()    {}

func (m *ListAddonRequest) GetAksAddon() *AKSAddon {
	if m != nil {
		return m.AksAddon
	}
	return nil
}

type ListAddonResponse struct {
	Output *Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *ListAddonResponse) Reset()         { *m = ListAddonResponse{} }
func (m *ListAddonResponse) String() string { return proto.CompactTextString(m) }
func (*ListAddonResponse) ProtoMessage()    {}

func (m *ListAddonResponse) GetOutput() *Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
}
