/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	syncv1alpha1 "Hybrid_Cluster/pkg/apis/sync/v1alpha1"
	versioned "Hybrid_Cluster/pkg/client/sync/v1alpha1/clientset/versioned"
	internalinterfaces "Hybrid_Cluster/pkg/client/sync/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "Hybrid_Cluster/pkg/client/sync/v1alpha1/listers/sync/v1alpha1"
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SyncInformer provides access to a shared informer and lister for
// Syncs.
type SyncInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SyncLister
}

type syncInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSyncInformer constructs a new informer for Sync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSyncInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSyncInformer constructs a new informer for Sync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HcpV1alpha1().Syncs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HcpV1alpha1().Syncs(namespace).Watch(context.TODO(), options)
			},
		},
		&syncv1alpha1.Sync{},
		resyncPeriod,
		indexers,
	)
}

func (f *syncInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSyncInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *syncInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&syncv1alpha1.Sync{}, f.defaultInformer)
}

func (f *syncInformer) Lister() v1alpha1.SyncLister {
	return v1alpha1.NewSyncLister(f.Informer().GetIndexer())
}
