// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegister) DeepCopyInto(out *ClusterRegister) {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = ClusterRegisterSpec{
		Platform:      in.Spec.Platform,
		Resourcegroup: in.Spec.Resourcegroup,
		Projectid:     in.Spec.Projectid,
		Clustername:   in.Spec.Clustername,
		Region:        in.Spec.Region,
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegister.
func (in *ClusterRegister) DeepCopy() *ClusterRegister {
	if in == nil {
		return nil
	}
	out := new(ClusterRegister)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRegister) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegisterList) DeepCopyInto(out *ClusterRegisterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRegister, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegisterList.
func (in *ClusterRegisterList) DeepCopy() *ClusterRegisterList {
	if in == nil {
		return nil
	}
	out := new(ClusterRegisterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRegisterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegisterSpec) DeepCopyInto(out *ClusterRegisterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegisterSpec.
func (in *ClusterRegisterSpec) DeepCopy() *ClusterRegisterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRegisterSpec)
	in.DeepCopyInto(out)
	return out
}
