// Code generated by protoc-gen-go.
// source: protos/v1/algo/algo.proto
// DO NOT EDIT!

/*
Package Hybrid_Cluster_protos_v1_algo is a generated protocol buffer package.

It is generated from these files:
	protos/v1/algo/algo.proto

It has these top-level messages:
	WeightResult
	ClusterWeightCalculatorRequest
	ClusterWeightCalculatorResponse
*/
package algo

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type WeightResult struct {
	ClusterId     int32  `protobuf:"varint,1,opt,name=cluster_id" json:"cluster_id,omitempty"`
	ClusterName   string `protobuf:"bytes,2,opt,name=cluster_name" json:"cluster_name,omitempty"`
	ClusterWeight int32  `protobuf:"varint,3,opt,name=cluster_weight" json:"cluster_weight,omitempty"`
}

func (m *WeightResult) Reset()         { *m = WeightResult{} }
func (m *WeightResult) String() string { return proto.CompactTextString(m) }
func (*WeightResult) ProtoMessage()    {}

// client - scheduler
type ClusterWeightCalculatorRequest struct {
}

func (m *ClusterWeightCalculatorRequest) Reset()         { *m = ClusterWeightCalculatorRequest{} }
func (m *ClusterWeightCalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterWeightCalculatorRequest) ProtoMessage()    {}

// server - AnalyticEngine
type ClusterWeightCalculatorResponse struct {
	WeightResult []*WeightResult `protobuf:"bytes,1,rep,name=weight_result" json:"weight_result,omitempty"`
}

func (m *ClusterWeightCalculatorResponse) Reset()         { *m = ClusterWeightCalculatorResponse{} }
func (m *ClusterWeightCalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterWeightCalculatorResponse) ProtoMessage()    {}

func (m *ClusterWeightCalculatorResponse) GetWeightResult() []*WeightResult {
	if m != nil {
		return m.WeightResult
	}
	return nil
}

func init() {
}
